project:
  type: website
  output-dir: docs

website:
  title: "NM Hockey Demo"
  favicon: images/general/favicon.jpg
  navbar:
    left:
      - text: Information
        menu:
        - text: "Season Details"
          href: league/season-details.qmd
        - text: "Payment Methods"
          href: league/payment-methods.qmd
        - text: "New or Returning Player Information"
          href: league/player-info.qmd
        - text: "Rules"
          href: league/rules.qmd
      - text: About
        menu:
          - text: "the League"
            href: league/league.qmd
          - text: "the Staff"
            href: league/staff.qmd
          - text: "the History"
            href: league/history.qmd
          - text: "Norski Cup"
            href: league/norski-cup.qmd
          - text: "Sportsmanship Award"
            href: league/sportsmanship-award.qmd
          - text: "Jerseys & Patches"
            href: league/jersey-patches.qmd
          - text: "Photos"
            href: league/photos.qmd
      - text: E Div
        menu:
          - text: "Teams"
            href: divisions/Ediv/teams.qmd
          - text: "Standings"
            href: divisions/Ediv/standings.qmd
          - text: "Goalies"
            href: divisions/Ediv/goalies.qmd
          - text: "Scores"
            href: divisions/Ediv/scores.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    toggle: true
    toc: true
    page-layout: full
    css: styles.css
    number-sections: true
    # other themes: Spacelab

editor: source

execute:
  echo: false

